export default {
  URL: 'https://startreflect.herokuapp.com',

  CHANGE_EDIT_USER_NAME: 'CHANGE_EDIT_USER_NAME',
  CHANGE_EDIT_USER_EMAIL: 'CHANGE_EDIT_USER_EMAIL',
  EDIT_USER: 'EDIT_USER',
  SAVE_EDIT_USER_REQUEST: 'SAVE_EDIT_USER_REQUEST',
  SAVE_EDIT_USER_SUCCESS: 'SAVE_EDIT_USER_SUCCESS',
  SAVE_EDIT_USER_FAIL: 'SAVE_EDIT_USER_FAIL',

  SET_LOADING: 'SET_LOADING',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_FAIL: 'CREATE_USER_FAIL',

  CREATE_NEW_ANSWER: 'CREATE_NEW_ANSWER',

  LOAD_ANSWER: 'LOAD_ANSWER',

  SAVE_ANSWER: 'SAVE_ANSWER',
  SAVE_ANSWER_OFFLINE: 'SAVE_ANSWER_OFFLINE',

  CHANGE_ANSWER_TEXT: 'CHANGE_ANSWER_TEXT',

  ADD_DAILY_PROMPT: 'ADD_DAILY_PROMPT',
  REMOVE_DAILY_PROMPT: 'REMOVE_DAILY_PROMPT',
  ADD_DAILY_PROMPT_OFFLINE: 'ADD_DAILY_PROMPT_OFFLINE',
  REMOVE_DAILY_PROMPT_OFFLINE: 'REMOVE_DAILY_PROMPT_OFFLINE',
  ADD_FAVORITE_PROMPT: 'ADD_FAVORITE_PROMPT',
  REMOVE_FAVORITE_PROMPT: 'REMOVE_FAVORITE_PROMPT',
  ADD_FAVORITE_PROMPT_OFFLINE: 'ADD_FAVORITE_PROMPT_OFFLINE',
  REMOVE_FAVORITE_PROMPT_OFFLINE: 'REMOVE_FAVORITE_PROMPT_OFFLINE',
  ADD_SAVE_PROMPT: 'ADD_SAVE_PROMPT',
  REMOVE_SAVE_PROMPT: 'REMOVE_SAVE_PROMPT',
  ADD_SAVE_PROMPT_OFFLINE: 'ADD_SAVE_PROMPT_OFFLINE',
  REMOVE_SAVE_PROMPT_OFFLINE: 'REMOVE_SAVE_PROMPT_OFFLINE',

  CHANGE_SEARCH: 'CHANGE_SEARCH',

  LOAD_CATEGORY: 'LOAD_CATEGORY',
  LOAD_LIST: 'LOAD_LIST',
  LOAD_LIST_TITLE: 'LOAD_LIST_TITLE',

  DELETE_ANSWER: 'DELETE_ANSWER',
  DELETE_ANSWER_OFFLINE: 'DELETE_ANSWER_OFFLINE',

  CHANGE_NEW_PROMPT_TITLE: 'CHANGE_NEW_PROMPT_TITLE',
  PICK_NEW_PROMPT_CATEGORY: 'PICK_NEW_PROMPT_CATEGORY',
  CREATE_NEW_PROMPT: 'CREATE_NEW_PROMPT',
  CREATE_NEW_PROMPT_OFFLINE: 'CREATE_NEW_PROMPT_OFFLINE',
  CLEAR_NEW_PROMPT: 'CLEAR_NEW_PROMPT',

  CHANGE_LOGIN_NAME: 'CHANGE_LOGIN_NAME',
  CHANGE_LOGIN_EMAIL: 'CHANGE_LOGIN_EMAIL',
  CHANGE_LOGIN_PASSWORD: 'CHANGE_LOGIN_PASSWORD',
  SIGNUP_USER_REQUEST: 'SIGNUP_USER_REQUEST',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
  CLEAR_LOGIN: 'CLEAR_LOGIN',
  LOAD_LOGIN: 'LOAD_LOGIN',

  LOGOUT: 'LOGOUT',

  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  LOAD_APPROVED_PROMPTS_SUCCESS: 'LOAD_APPROVED_PROMPTS_SUCCESS',

  LOAD_USER_PROMPTS_SUCCESS: 'LOAD_USER_PROMPTS_SUCCESS',
  LOAD_USER_ANSWERS_SUCCESS: 'LOAD_USER_ANSWERS_SUCCESS',
  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',

  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',

  UPDATE_STREAK: 'UPDATE_STREAK',
  UPDATE_STREAK_SUCCESS: 'UPDATE_STREAK_SUCCESS',
  UPDATE_STREAK_OFFLINE: 'UPDATE_STREAK_OFFLINE',
  RESET_STREAK: 'RESET_STREAK',
  RESET_STREAK_SUCCESS: 'RESET_STREAK_SUCCESS',
  RESET_STREAK_OFFLINE: 'RESET_STREAK_OFFLINE',

  LOAD_TODAY_PROMPT_SUCCESS: 'LOAD_TODAY_PROMPT_SUCCESS',

  RESET_SEEN: 'RESET_SEEN',

  OFFLINE_SAVE: 'OFFLINE_SAVE',
  OFFLINE_SAVE_SUCCESS: 'OFFLINE_SAVE_SUCCESS',
  OFFLINE_SAVE_FAIL: 'OFFLINE_SAVE_FAIL'
};
